#!/bin/bash -e

setup_radosgw_apache()
{
	echo "setup_rados_gw_apache"
}

unconfigure_radosgw_apache()
{
	echo "unconfigure_rados_gw_apache"
}


case "$1" in
	configure)
		setup_radosgw_apache
		/etc/init.d/apache2 stop
		/etc/init.d/apache2 start
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		unconfigure_radosge_apache
		/etc/init.d/apache2 stop
		:
		;;
	*)
		echo "postinst called with unknown argument $1" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
