#!/bin/bash -e

case "$1" in
	remove)
		[ -e /etc/radosgw-apache/radosgw-apache.conf ] && \
			rm -f /etc/radosgw-apache/radosgw-apache.conf
		[ -e /etc/default/radosgw-apache.orig ] && \
			mv /etc/default/radosgw-apache.orig /etc/default/radosgw-apache
		/etc/init.d/apache2 stop
		;;
	upgrade|deconfigure)
		:
		;;
	*)
		echo "prerm called with unknown argument $1" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
