#!/bin/bash -e

setup_radosgw_apache()
{
	echo "setup_rados_gw_apache"
}

unconfigure_radosgw_apache()
{
	echo "unconfigure_rados_gw_apache"
}


case "$1" in
	configure)
		setup_radosgw_apache
		[ -x /sbin/start ] && (stop apache || true) && start apache
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		unconfigure_radosge_apache
		[ -x /sbin/stop ] && (stop apache || true)
		:
		;;
	*)
		echo "postinst called with unknown argument $1" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
