#!/bin/bash -e

unconfigure_radosgw_apache()
{
	[ -e /etc/radosgw-apache/radosgw-apache.conf ] && \
		rm -f /etc/radosgw-apache/radosgw-apache.conf
	[ -e /etc/default/radosgw-apache.orig ] && \
		mv /etc/default/radosgw-apache.orig /etc/default/radosgw-apache
}

case "$1" in
	remove)
		unconfigure_radosgw-apache
		[ -x /sbin/stop ] && stop apache
		;;
	upgrade|deconfigure)
		:
		;;
	*)
		echo "prerm called with unknown argument $1" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
